# Generated by Django 4.0.2 on 2022-04-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0002_modeuser2'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeuser',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='modeuser2',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
