# Generated by Django 4.0.2 on 2022-04-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0003_modeuser_date_modeuser2_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeuser',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='modeuser2',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
