# Generated by Django 4.0.2 on 2022-03-22 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.IntegerField(help_text='This is Age', null=True, verbose_name='Age')),
            ],
        ),
        migrations.CreateModel(
            name='MyModelForm',
            fields=[
                ('mymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.mymodel')),
            ],
            bases=('app1.mymodel',),
        ),
    ]
