# Generated by Django 4.0.2 on 2022-03-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='first',
            field=models.CharField(help_text='This is First Name', max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.DeleteModel(
            name='MyModelForm',
        ),
    ]
