# Generated by Django 4.0.2 on 2022-03-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_mymodel_first_delete_mymodelform'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='age',
            field=models.IntegerField(help_text='This is Age', null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='last',
            field=models.CharField(help_text='This is Last Name', max_length=50, null=True, verbose_name='Last Name'),
        ),
    ]
